name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-multilib libc6-dev-i386 grub-pc-bin xorriso

      - name: Build
        run: |
          make

      - name: Upload ISO artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: boot-iso
          path: build/boot.iso
